name: PR Comment and Update from File
author: Ethan Graf <ethan.graf@fuzzbuzz.io>
description: Leaves a comment on an open PR based on the contents of a file. If a comment with the right prefix exists, update instead. Based off PR Comment action by Alexander Matheson.
branding:
  icon: 'message-square'  
  color: 'black'
inputs:
  path: 
    description: file path
    required: true
  prefix:
    description: comment prefix
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.prefix }}